# Generated by Django 6.1.1 on 2026-09-24 21:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0012_remove_estudiocarga_usuario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('LEV', 'Levantamiento en sitio'), ('VFU', 'Visita fuera de ciudad'), ('ANT', 'Anteproyecto'), ('LAM', 'Lámina planimétrica'), ('TAB', 'Diseño de tableros'), ('UNI', 'Unifilar / cuadro de cargas'), ('MEM', 'Memoria técnica y de cálculo'), ('FIR', 'Firma profesional'), ('RED', 'Red estructurada (data/voz)'), ('CCTV', 'CCTV / seguridad electrónica'), ('ALA', 'Alarma (intrusión / incendio)'), ('APU', 'Presupuesto referencial (APU)'), ('DIG', 'Digitalización / impresión')], default='LAM', max_length=4)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.CharField(blank=True, max_length=220)),
                ('precio_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unidad', models.CharField(choices=[('UN', 'Unidad'), ('M2', 'Metro cuadrado (m²)'), ('LAM', 'Lámina planimétrica'), ('VIS', 'Visita'), ('TBL', 'Tablero'), ('CIR', 'Circuito')], default='UN', max_length=3)),
                ('editable', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Entregable de planos',
                'verbose_name_plural': 'Catálogo de entregables de planos',
                'ordering': ['categoria', 'orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PlanParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=24)),
                ('fuente', models.CharField(blank=True, max_length=120)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parámetro del cotizador de planos',
                'verbose_name_plural': 'Parámetros del cotizador de planos',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionPlanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.CharField(blank=True, max_length=220)),
                ('tipo_proyecto', models.CharField(choices=[('RES', 'Residencial'), ('COM', 'Comercial'), ('IND', 'Industrial')], default='RES', max_length=3)),
                ('area_m2', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=9, verbose_name='Área (m²)')),
                ('n_tableros', models.PositiveIntegerField(default=1, verbose_name='Nº tableros')),
                ('n_circuitos', models.PositiveIntegerField(default=1, verbose_name='Nº circuitos')),
                ('integral', models.BooleanField(default=False, verbose_name='Proyecto integral (eléctrico + electrónico)')),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_planos', to='crm.client')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_planos', to='crm.proforma')),
            ],
            options={
                'verbose_name': 'Cotización de planos',
                'verbose_name_plural': 'Cotizaciones de planos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RubroCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=220)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=9)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='plans.cotizacionplanos')),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubros', to='plans.entregable')),
            ],
            options={
                'verbose_name': 'Rubro de la cotización',
                'verbose_name_plural': 'Rubros de la cotización',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
