# Generated by Django 6.1.1 on 2026-09-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planparametro',
            name='valor',
            field=models.CharField(max_length=300),
        ),
    ]
