# Generated by Django 6.1.1 on 2026-09-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_planparametro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionplanos',
            name='plano_arquitectonico',
            field=models.BooleanField(default=True, verbose_name='Dispone de plano arquitectónico (ej. CAD del arquitecto)'),
        ),
    ]
