# Generated by Django 5.2.8 on 2026-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detailed_information',
            field=models.TextField(blank=True),
        ),
    ]
