# Generated by Django 6.1.1 on 2026-09-19 17:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proforma',
            name='description',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='total',
        ),
        migrations.AddField(
            model_name='client',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, verbose_name='R.U.C. / C.I.'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='client_address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='proforma',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proforma',
            name='client_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='proforma',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='proforma',
            name='client_ruc',
            field=models.CharField(blank=True, max_length=30, verbose_name='R.U.C. / C.I.'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='proforma',
            name='object_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proforma',
            name='place',
            field=models.CharField(default='Quito', max_length=80),
        ),
        migrations.AddField(
            model_name='proforma',
            name='scope_text',
            field=models.TextField(blank=True, help_text='Un punto del alcance por línea.'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='service_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='proforma',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='proforma',
            name='terms_text',
            field=models.TextField(blank=True, help_text='Un término por línea.'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='title',
            field=models.CharField(default='PROPUESTA ECONÓMICA', max_length=120),
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.proforma')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
