# Generated by Django 6.1.1 on 2026-09-20 01:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_proforma_description_remove_proforma_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribuidoraNEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('provincia', models.CharField(blank=True, max_length=80)),
                ('sistema', models.CharField(default='Monofásica', max_length=60)),
                ('frecuencia_hz', models.CharField(default='60', max_length=10)),
                ('voltaje_suministro', models.CharField(default='120/240 V', max_length=20)),
                ('potencia_max_residencial', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('requisitos_medicion', models.CharField(blank=True, max_length=220)),
                ('norma_acometida', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Distribuidoras eléctricas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('version', models.CharField(max_length=40)),
                ('titulo', models.CharField(blank=True, max_length=180)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Normas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CargaNormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('ILU', 'Iluminación'), ('TOM', 'Tomacorrientes'), ('ELE', 'Electrodomésticos'), ('MOT', 'Motores'), ('HVAC', 'HVAC / Aire acondicionado'), ('COM', 'Comercial'), ('IND', 'Industrial'), ('EV', 'Carga de vehículos EV'), ('SOL', 'Solar')], default='ELE', max_length=4)),
                ('equipo', models.CharField(max_length=120)),
                ('unidad', models.CharField(choices=[('W', 'W'), ('kW', 'kW'), ('VA', 'VA'), ('kVA', 'kVA'), ('HP', 'HP')], default='W', max_length=5)),
                ('potencia', models.DecimalField(decimal_places=2, default=Decimal('1800.00'), max_digits=10)),
                ('factor_demanda', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='Factor demanda %')),
                ('factor_potencia', models.DecimalField(decimal_places=3, default=Decimal('0.90'), max_digits=5, verbose_name='Factor potencia')),
                ('voltaje', models.CharField(default='220 V', max_length=20)),
                ('fases', models.CharField(choices=[('1F', 'Monofásica'), ('2F', 'Bifásica'), ('3F', 'Trifásica')], default='1F', max_length=2)),
                ('tipo_carga', models.CharField(choices=[('RES', 'Resistiva'), ('IND', 'Inductiva'), ('MOT', 'Motriz')], default='RES', max_length=3)),
                ('metodo_calculo', models.CharField(blank=True, max_length=120)),
                ('editable', models.BooleanField(default=True, verbose_name='Editable por diseñador')),
                ('obs_tecnica', models.CharField(blank=True, max_length=220, verbose_name='Observación técnica')),
                ('activa', models.BooleanField(default=True)),
                ('distribuidora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='crm.distribuidoranec')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='crm.norma')),
            ],
            options={
                'verbose_name_plural': 'Catálogo de cargas normativas',
                'ordering': ['categoria', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=40)),
                ('valor_antes', models.CharField(blank=True, max_length=60)),
                ('valor_despues', models.CharField(blank=True, max_length=60)),
                ('motivo', models.CharField(blank=True, max_length=180)),
                ('usuario', models.CharField(blank=True, max_length=120)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='crm.carganormativa')),
            ],
            options={
                'verbose_name_plural': 'Historial de cambios de carga',
                'ordering': ['-fecha'],
            },
        ),
    ]
