# Generated by Django 6.1.1 on 2026-09-20 20:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_distribuidoranec_norma_carganormativa_historialcarga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('fuente', models.CharField(max_length=120, verbose_name='Fuente normativa')),
                ('referencia', models.CharField(blank=True, max_length=120, verbose_name='Referencia')),
                ('version', models.CharField(default='2025', max_length=20)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Parámetros normativos',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='EstudioCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=220)),
                ('voltaje_linea', models.DecimalField(decimal_places=1, default=Decimal('220.0'), max_digits=6, verbose_name='Voltaje línea (V)')),
                ('servicio', models.CharField(choices=[('1F', 'Monofásico'), ('3F', 'Trifásico')], default='1F', max_length=20, verbose_name='Servicio')),
                ('caida_tension_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Caída de tensión máx %')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='crm.client')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Estudios de carga',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('potencia_kw', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Potencia kW')),
                ('factor_demanda', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='FD %')),
                ('factor_potencia', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='FP')),
                ('fase', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Fase destino')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_estudios', to='crm.carganormativa')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.estudiocarga')),
            ],
            options={
                'verbose_name_plural': 'Ítems del estudio',
                'ordering': ['id'],
            },
        ),
    ]
