# Generated by Django 6.1.1 on 2026-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_estudios_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiocarga',
            name='conductor_material',
            field=models.CharField(choices=[('Cu', 'Cobre'), ('Al', 'Aluminio')], default='Cu', max_length=6, verbose_name='Material conductor'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='longitud_linea',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Longitud de línea (m)'),
        ),
    ]
