# Generated by Django 6.1.1 on 2026-09-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_estudio_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiocarga',
            name='servicio',
            field=models.CharField(choices=[('1F', 'Monofásico'), ('2F', 'Bifásico'), ('3F', 'Trifásico')], default='1F', max_length=20, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='itemestudio',
            name='fase',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('', 'Auto')], default='', max_length=1, verbose_name='Fase destino'),
        ),
    ]
