# Generated by Django 6.1.1 on 2026-09-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_servicio_2f_fase_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RES', 'Residencial'), ('COM', 'Comercial'), ('OFI', 'Oficinas')], max_length=3)),
                ('hora', models.PositiveSmallIntegerField(verbose_name='Hora (0-23)')),
                ('factor', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Factor demanda %')),
            ],
            options={
                'verbose_name_plural': 'Perfiles horarios de demanda',
                'ordering': ['tipo', 'hora'],
                'unique_together': {('tipo', 'hora')},
            },
        ),
    ]
