# Generated by Django 6.1.1 on 2026-09-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_perfil_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carganormativa',
            name='categoria',
            field=models.CharField(choices=[('ILU', 'Iluminación'), ('TOM', 'Tomacorrientes'), ('ELE', 'Electrodomésticos'), ('MOT', 'Motores'), ('HVAC', 'HVAC / Aire acondicionado'), ('COM', 'Comercial'), ('IND', 'Industrial'), ('EV', 'Carga de vehículos EV'), ('SOL', 'Solar'), ('OTR', 'Otros')], default='ELE', max_length=4),
        ),
    ]
