# Generated by Django 6.1.1 on 2026-09-22 20:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def retro_ff_fs(apps, schema_editor):
    """Backfill EEQ: los ítems existentes conservaban FD% = factor_demanda.
    Se mapean a FFUn=100 % y FSn=FD% para mantener el cálculo previo."""
    ItemEstudio = apps.get_model('crm', 'ItemEstudio')
    for it in ItemEstudio.objects.all():
        it.ffun = Decimal('100.00')
        it.fsn = it.factor_demanda
        it.save(update_fields=['ffun', 'fsn'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_categoria_otros'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiocarga',
            name='actividad_tipo',
            field=models.CharField(blank=True, max_length=60, verbose_name='Actividad tipo'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='expediente_eeq',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nº expediente EEQ'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='fecha_estudio',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del estudio'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='ingeniero_responsable',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ingeniero responsable'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='localizacion',
            field=models.CharField(blank=True, max_length=180, verbose_name='Localización'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='numero_usuarios',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de usuarios'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='registro_lp',
            field=models.CharField(blank=True, max_length=60, verbose_name='Registro LP'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='usuario_tipo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Usuario tipo'),
        ),
        migrations.AddField(
            model_name='itemestudio',
            name='ffun',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='FFUn % (funcionamiento unitario)'),
        ),
        migrations.AddField(
            model_name='itemestudio',
            name='fsn',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='FSn % (servicio/simultaneidad)'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Zona')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='crm.estudiocarga')),
            ],
            options={
                'verbose_name_plural': 'Zonas del estudio',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itemestudio',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='crm.zona'),
        ),
        migrations.RunPython(
            code=retro_ff_fs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
