# Generated by Django 6.1.1 on 2026-09-23 23:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_estudiocarga_renombrar_voltaje_fase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorDiversidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_usuarios', models.PositiveIntegerField(verbose_name='Nº abonados (N)')),
                ('factor', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Factor de diversidad (FD)')),
            ],
            options={
                'verbose_name_plural': 'Factores de diversidad comerciales (A-11-D1)',
                'ordering': ['numero_usuarios'],
            },
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='dap_kw',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8, verbose_name='DAP — Alumbrado público (kW)'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='es_camara_transformacion',
            field=models.BooleanField(default=False, verbose_name='Cámara de transformación (DPT 1.0 %)'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='estrato',
            field=models.CharField(blank=True, choices=[('A1', 'A1 (501–900 kWh/mes)'), ('A', 'A (351–500)'), ('B', 'B (251–350)'), ('C', 'C (151–250)'), ('D', 'D (101–150)'), ('E', 'E (0–100)')], max_length=2, null=True, verbose_name='Estrato de consumo'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='fd_factor_diversidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='FD factor de diversidad (auto si vacío)'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='n_abonados_comercial',
            field=models.PositiveIntegerField(default=1, verbose_name='N — Abonados que inciden en el punto'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='subestacion_taps',
            field=models.BooleanField(default=False, verbose_name='Subestación con taps bajo carga'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='tipo_estudio',
            field=models.CharField(choices=[('RES', 'Residencial (DMD por estrato)'), ('COM', 'Comercial/Industrial (DMU × N / FD)')], default='COM', max_length=3, verbose_name='Tipo de estudio'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='usuarios_proyectados',
            field=models.PositiveIntegerField(default=0, verbose_name='Usuarios proyectados (período diseño)'),
        ),
        migrations.AddField(
            model_name='estudiocarga',
            name='zona_urbano_rural',
            field=models.CharField(choices=[('URB', 'Urbano'), ('RUR', 'Rural')], default='URB', max_length=3, verbose_name='Zona'),
        ),
        migrations.CreateModel(
            name='DMDResidencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_usuarios', models.PositiveIntegerField(verbose_name='Nº usuarios')),
                ('estrato', models.CharField(choices=[('A1', 'A1 (501–900 kWh/mes)'), ('A', 'A (351–500)'), ('B', 'B (251–350)'), ('C', 'C (151–250)'), ('D', 'D (101–150)'), ('E', 'E (0–100)')], max_length=2, verbose_name='Estrato')),
                ('dmd_kw', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='DMD (kW)')),
            ],
            options={
                'verbose_name_plural': 'Demandas máximas diversificadas residenciales (A-11.03_1)',
                'ordering': ['estrato', 'numero_usuarios'],
                'unique_together': {('numero_usuarios', 'estrato')},
            },
        ),
    ]
