# Generated by Django 6.1.1 on 2026-09-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_factordiversidad_estudiocarga_dap_kw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiocarga',
            name='usuario_tipo',
        ),
    ]
